# Generated by Django 4.2.5 on 2023-09-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('is_vegan', models.BooleanField()),
            ],
        ),
    ]
