# Generated by Django 4.2.5 on 2023-10-16 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0004_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="like_users",
            field=models.ManyToManyField(
                related_name="like_articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
